project_id = "wybkixbkhgfqcmmrczbl"

[functions.analyze-document]
verify_jwt = true

[functions.init-admin]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.admin-delete-user]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true

[functions.send-2fa-code]
verify_jwt = false

[functions.verify-2fa-code]
verify_jwt = false
